[2025-07-09T05:05:14.891+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T05:05:14.947+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_call_python_file.extract_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:05:14.963+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_call_python_file.extract_task manual__2025-07-09T05:03:18.296639+00:00 [queued]>
[2025-07-09T05:05:14.964+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-09T05:05:14.989+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_task> on 2025-07-09 05:03:18.296639+00:00
[2025-07-09T05:05:15.013+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'bash_call_python_file', 'extract_task', 'manual__2025-07-09T05:03:18.296639+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp_k2yb8vr']
[2025-07-09T05:05:15.021+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=226) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-09T05:05:15.022+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask extract_task
[2025-07-09T05:05:15.022+0000] {standard_task_runner.py:63} INFO - Started process 227 to run task
[2025-07-09T05:05:15.197+0000] {task_command.py:426} INFO - Running <TaskInstance: bash_call_python_file.extract_task manual__2025-07-09T05:03:18.296639+00:00 [running]> on host fe3fd911cec1
[2025-07-09T05:05:15.692+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bash_call_python_file' AIRFLOW_CTX_TASK_ID='extract_task' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T05:03:18.296639+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T05:03:18.296639+00:00'
[2025-07-09T05:05:15.698+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T05:05:15.995+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-09T05:05:15.997+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T05:05:16.019+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bash_call_python_file, task_id=extract_task, run_id=manual__2025-07-09T05:03:18.296639+00:00, execution_date=20250709T050318, start_date=20250709T050514, end_date=20250709T050516
[2025-07-09T05:05:16.083+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-09T05:05:16.132+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-09T05:05:16.137+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
